### ISSUE TITLE
Graph not showing

### ISSUE THREAD

**Issue by surbhiagrawal22** [nmalkin/plot-likert#28] opened 2022-02-07 21:48 UTC
Earlier 5 days back, i wrote the same code and I was able to plot the Likert plot

But now running today, no graph is displayed

# Plotting The Likert Scale Graph for Perceived stress columns using library https://github.com/nmalkin/plot-likert
#!pip3 install git+https://github.com/nmalkin/plot-likert.github
!pip3 install plot-likert

```
import plot_likert
scale = [     "Never" , 
              "Almost never" ,
              "Sometimes" , 
              "Fairly often" ,
              "Very often" 
        ]

try:
    ax=plot_likert.plot_likert(PSS_scale_columns,scale,colors=plot_likert.colors.likert5,figsize=(50,80),xtick_interval=10);
    ax.figure.set_size_inches(20, 30)
    column_list=PSS_scale_columns.columns.tolist()
    #column_list.reverse()
    ax.xaxis.set_label_text('Percentage of responses');
    ax.set_title("Likert Graph for PSS columns ");
    ax.set_yticklabels(column_list)
    print("happy")
except plot_likert.PlotLikertError as e:
    import sys
    print("sad")
    print("Oh no, something went wrong! The message in the exception is:\n" + str(e), file=sys.stderr)
```

Only happy is being printed

**Comment by nmalkin** [comment] 2022-02-08 00:26
Hi! I tried to reproduce your error but was able to generate the graphs without any problems, using both the stable version and the latest version on Github:

![image](https://user-images.githubusercontent.com/903179/152894528-cfe72c9b-5e9a-4486-a97f-6a46557a1440.png)

Are you able to reproduce this behavior with a clean virtual environment and/or a different machine?

**Comment by surbhiagrawal22** [comment] 2022-02-08 00:50
The code is working fine if i run your above code in a clean environment

Just another question , how to handle missing values for questions where user did not answer.
My questions columns consists of NaN values , that why may be not producing the graph

**Comment by nmalkin** [comment] 2022-02-08 06:50
Generally, NaN values should be handled without problems; for example, see the ["Missing data" section in the guide](https://github.com/nmalkin/plot-likert/blob/master/docs/guide.ipynb#Missing-data).

Here's an example with your code:
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/903179/152932040-0d52f411-b178-4f2f-9166-8a1a1af8d127.png">

In coming up with an example, I discovered a bug that would occur with certain types of null values (08e96d5). I'm guessing it wasn't affecting you, because you would've seen a `TypeError`, but if you do get one of those, you can update to the latest development version.

**Comment by surbhiagrawal2020** [comment] 2022-02-11 17:46
TypeError: plot_likert() got an unexpected keyword argument 'compute_percentages'
Getting this error , though i am using latest veriosn of plot_likert library

**Comment by alaskamike** [comment] 2022-02-11 18:18
Add plot_percentage=False to your call to plot_likert.

**Comment by nmalkin** [comment] 2022-02-11 23:12
I think the issue might be that `compute_percentages` is an argument to
`plot_counts` rather than `plot_likert`.

**Comment by nmalkin** [comment] 2022-03-17 05:49
Closing this out, but let me know if there are any remaining issues

**Closed by nmalkin** 2022-03-17 05:49 UTC
